export const emoji = {
  dashboard: "🏠",
  transaksi: "🧾",
  laporan: "📊",
  project: "🏗️",
  master: "🗃️",
  coa: "🔢",
  kontak: "👥",
  kasBank: "💰",
  aset: "🧰",
  pajak: "🏷️",
  periode: "🗓️",
  audit: "🕵️",
  perusahaan: "🏢",
  profil: "👤",
  pengaturan: "⚙️",
  keluar: "🚪",
  tambah: "➕",
  simpan: "💾",
  posting: "✅",
  ubah: "✏️",
  hapus: "🗑️",
  duplikat: "📋",
  balik: "↩️",
  pecah: "✂️",
  cari: "🔍",
  lihat: "👁️",
  impor: "📥",
  ekspor: "📤",
  cetak: "🖨️",
  unduh: "⬇️",
  lampiran: "📎",
  kirim: "✉️",
  muat: "🔄",
  kunci: "🔒",
  buka: "🔓",
  paket: "📦",
  batal: "❌",
  draft: "⏳",
  peringatan: "⚠️",
  kasMasuk: "💵",
  kasKeluar: "💸",
} as const;

export type EmojiKey = keyof typeof emoji;
